name: here4help
description: NCCU Social Task Posting APP  - Here4help.

publish_to: 'none'

version: 1.2.1+20250717

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  intl: ^0.18.1   
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  geolocator: ^14.0.1
  go_router: ^13.1.0
  provider: ^6.1.0
  http: ^1.4.0
  flutter_slidable: ^3.0.0
  socket_io_client: ^2.0.3
  # Google 登入套件 (跨平台)
  google_sign_in: ^6.2.1
  googleapis_auth: ^1.4.1
  # Facebook 登入套件
  flutter_facebook_auth: ^6.0.4
  # Apple 登入套件
  sign_in_with_apple: ^5.0.0
  # 平台檢測
  universal_platform: ^1.0.0+1
  image_picker: ^1.0.7
  infinite_scroll_pagination: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon/AppIcon.png'
  
  

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/demoData/
    - assets/images/avatar/
    - assets/icon/
