final List<Map<String, dynamic>> testAccounts = [
  {
    'id': 1,
    'name': 'Michael',
    'email': 'mchaell@nccu.edu.test',
    'password': 'admin1234',
    'permission': 99,
    'avatar_url': 'assets/images/avatar/avatar-4.png',
    'points': 999,
    'language_requirement': 'English',
  },
  {
    'id': 2,
    'name': 'Luisa',
    'email': 'luisa123@nccu.edu.test',
    'password': 'user5678',
    'permission': 1,
    'avatar_url': 'assets/images/avatar/avatar-1.png',
    'points': 120,
    'language_requirement': 'English',
  },
  {
    'id': 3,
    'name': 'Linda',
    'email': 'ld321@nccu.edu.test',
    'password': 'user5678',
    'permission': 1,
    'avatar_url': 'assets/images/avatar/avatar-2.png',
    'points': 80,
    'language_requirement': 'English',
  },
  {
    'id': 4,
    'name': 'Chris',
    'email': 'ch1234@nccu.edu.test',
    'password': 'user5678',
    'permission': 0,
    'avatar_url': 'assets/images/avatar/avatar-3.png',
    'points': 0,
    'language_requirement': 'English',
  },
];
