final List<Map<String, dynamic>> testAccounts = [
  {
    'id': 1,
    'name': 'Michael',
    'email': 'Michael@test',
    'password': '1234',
    'permission': 99,
    'avatar_url': 'assets/images/avatar/avatar-4.png',
    'points': 1020,
    'language_requirement': 'English',
  },
  {
    'id': 2,
    'name': 'Luisa',
    'email': 'Luisa@test',
    'password': '1234',
    'permission': 1,
    'avatar_url': 'assets/images/avatar/avatar-1.png',
    'points': 1200,
    'language_requirement': 'English',
  },
  {
    'id': 3,
    'name': 'Linda',
    'email': 'linda@test',
    'password': '1234',
    'permission': 1,
    'avatar_url': 'assets/images/avatar/avatar-2.png',
    'points': 920,
    'language_requirement': 'English',
  },
  {
    'id': 4,
    'name': 'Chris',
    'email': 'chris@test',
    'password': '1234',
    'permission': 0,
    'avatar_url': 'assets/images/avatar/avatar-3.png',
    'points': 1234,
    'language_requirement': 'English',
  },
];
