const Map<String, String> languageMap = {
  "Abkhaz": "Abkhaz",
  "Acehnese": "Acehnese",
  "Acholi": "Acholi",
  "Afrikaans": "Afrikaans",
  "Amis (Taiwan)": "Amis (Taiwan)",
  "Arabic": "Arabic",
  "Azerbaijani": "Azerbaijani",
  "Bunun (Taiwan)": "Bunun (Taiwan)",
  "Bengali": "Bengali",
  "Catalan": "Catalan",
  "Cantonese": "Cantonese",
  "Chinese (Simplified)": "Chinese (Simplified)",
  "Chinese (Traditional)": "Chinese (Traditional)",
  "Czech": "Czech",
  "Welsh": "Welsh",
  "Danish": "Danish",
  "Dutch": "Dutch",
  "English": "English",
  "Estonian": "Estonian",
  "Persian": "Persian",
  "Finnish": "Finnish",
  "French": "French",
  "Irish": "Irish",
  "Galician": "Galician",
  "German": "German",
  "Greek": "Greek",
  "Gujarati": "Gujarati",
  "Hakka": "Hakka",
  "Haitian Creole": "Haitian Creole",
  "Hausa": "Hausa",
  "Hebrew": "Hebrew",
  "Hindi": "Hindi",
  "Hungarian": "Hungarian",
  "Icelandic": "Icelandic",
  "Indonesian": "Indonesian",
  "Italian": "Italian",
  "Japanese": "Japanese",
  "Kavalan (Taiwan)": "Kavalan (Taiwan)",
  "Kannada": "Kannada",
  "Korean": "Korean",
  "Kurdish (Kurmanji)": "Kurdish (Kurmanji)",
  "Lao": "Lao",
  "Latvian": "Latvian",
  "Lithuanian": "Lithuanian",
  "Malay": "Malay",
  "Malayalam": "Malayalam",
  "Marathi": "Marathi",
  "Mongolian": "Mongolian",
  "Taiwanese Hokkien": "Taiwanese Hokkien",
  "Nepali": "Nepali",
  "Norwegian (Bokmål)": "Norwegian (Bokmål)",
  "Punjabi (Gurmukhi)": "Punjabi (Gurmukhi)",
  "Punjabi (Shahmukhi)": "Punjabi (Shahmukhi)",
  "Polish": "Polish",
  "Portuguese (Brazil)": "Portuguese (Brazil)",
  "Portuguese (Portugal)": "Portuguese (Portugal)",
  "Paiwan (Taiwan)": "Paiwan (Taiwan)",
  "Romanian": "Romanian",
  "Russian": "Russian",
  "Sinhala": "Sinhala",
  "Slovak": "Slovak",
  "Slovenian": "Slovenian",
  "Spanish": "Spanish",
  "Swahili": "Swahili",
  "Swedish": "Swedish",
  "Tamil": "Tamil",
  "Atayal (Taiwan)": "Atayal (Taiwan)",
  "Telugu": "Telugu",
  "Thai": "Thai",
  "Turkish": "Turkish",
  "Ukrainian": "Ukrainian",
  "Urdu": "Urdu",
  "Uzbek": "Uzbek",
  "Vietnamese": "Vietnamese",
  "Yiddish": "Yiddish",
  "Zulu": "Zulu"
};
