// lib/constants/languages.dart
// Generated from DB table `languages` (code, name, native)

class Languages {
  static const List<Map<String, String>> all = [
    {'code': 'en', 'name': 'English', 'native': 'English'},
    {'code': 'zh', 'name': 'Chinese', 'native': '中文'},
    {'code': 'es', 'name': 'Spanish', 'native': 'Español'},
    {'code': 'fr', 'name': 'French', 'native': 'Français'},
    {'code': 'de', 'name': 'German', 'native': 'Deutsch'},
    {'code': 'ja', 'name': 'Japanese', 'native': '日本語'},
    {'code': 'ko', 'name': 'Korean', 'native': '한국어'},
    {'code': 'pt', 'name': 'Portuguese', 'native': 'Português'},
    {'code': 'ru', 'name': 'Russian', 'native': 'Русский'},
    {'code': 'ar', 'name': 'Arabic', 'native': 'العربية'},
    {'code': 'hi', 'name': 'Hindi', 'native': 'हिन्दी'},
    {'code': 'it', 'name': 'Italian', 'native': 'Italiano'},
    {'code': 'nl', 'name': 'Dutch', 'native': 'Nederlands'},
    {'code': 'sv', 'name': 'Swedish', 'native': 'Svenska'},
    {'code': 'da', 'name': 'Danish', 'native': 'Dansk'},
    {'code': 'no', 'name': 'Norwegian', 'native': 'Norsk'},
    {'code': 'fi', 'name': 'Finnish', 'native': 'Suomi'},
    {'code': 'pl', 'name': 'Polish', 'native': 'Polski'},
    {'code': 'tr', 'name': 'Turkish', 'native': 'Türkçe'},
    {'code': 'th', 'name': 'Thai', 'native': 'ไทย'},
    {'code': 'vi', 'name': 'Vietnamese', 'native': 'Tiếng Việt'},
    {'code': 'id', 'name': 'Indonesian', 'native': 'Bahasa Indonesia'},
    {'code': 'ms', 'name': 'Malay', 'native': 'Bahasa Melayu'},
    {'code': 'he', 'name': 'Hebrew', 'native': 'עברית'},
    {'code': 'el', 'name': 'Greek', 'native': 'Ελληνικά'},
    {'code': 'cs', 'name': 'Czech', 'native': 'Čeština'},
    {'code': 'hu', 'name': 'Hungarian', 'native': 'Magyar'},
    {'code': 'ro', 'name': 'Romanian', 'native': 'Română'},
    {'code': 'sk', 'name': 'Slovak', 'native': 'Slovenčina'},
    {'code': 'hr', 'name': 'Croatian', 'native': 'Hrvatski'},
    {'code': 'sl', 'name': 'Slovenian', 'native': 'Slovenščina'},
    {'code': 'et', 'name': 'Estonian', 'native': 'Eesti'},
    {'code': 'lv', 'name': 'Latvian', 'native': 'Latviešu'},
    {'code': 'lt', 'name': 'Lithuanian', 'native': 'Lietuvių'},
    {'code': 'bg', 'name': 'Bulgarian', 'native': 'Български'},
    {'code': 'mk', 'name': 'Macedonian', 'native': 'Македонски'},
    {'code': 'sr', 'name': 'Serbian', 'native': 'Српски'},
    {'code': 'uk', 'name': 'Ukrainian', 'native': 'Українська'},
    {'code': 'be', 'name': 'Belarusian', 'native': 'Беларуская'},
    {'code': 'ka', 'name': 'Georgian', 'native': 'ქართული'},
    {'code': 'hy', 'name': 'Armenian', 'native': 'Հայերեն'},
    {'code': 'az', 'name': 'Azerbaijani', 'native': 'Azərbaycan'},
    {'code': 'kk', 'name': 'Kazakh', 'native': 'Қазақ'},
    {'code': 'ky', 'name': 'Kyrgyz', 'native': 'Кыргызча'},
    {'code': 'uz', 'name': 'Uzbek', 'native': 'Oʻzbekcha'},
    {'code': 'zh-tg', 'name': 'Taiwanese', 'native': 'Tâi-uân-bûn(tâi-gí)'},
    {'code': 'zh-tw', 'name': 'Chinese (Traditional)', 'native': '中文（繁體）'},
    {'code': 'zh-cn', 'name': 'Chinese (Simplified)', 'native': '中文（簡體）'},
    {'code': 'tg', 'name': 'Tajik', 'native': 'Тоҷикӣ'},
    {'code': 'fa', 'name': 'Persian', 'native': 'فارسی'},
    {'code': 'ur', 'name': 'Urdu', 'native': 'اردو'},
    {'code': 'bn', 'name': 'Bengali', 'native': 'বাংলা'},
    {'code': 'ta', 'name': 'Tamil', 'native': 'தமிழ்'},
    {'code': 'te', 'name': 'Telugu', 'native': 'తెలుగు'},
    {'code': 'kn', 'name': 'Kannada', 'native': 'ಕನ್ನಡ'},
    {'code': 'ml', 'name': 'Malayalam', 'native': 'മലയാളം'},
    {'code': 'gu', 'name': 'Gujarati', 'native': 'ગુજરાતી'},
    {'code': 'pa', 'name': 'Punjabi', 'native': 'ਪੰਜਾਬੀ'},
    {'code': 'mr', 'name': 'Marathi', 'native': 'मराठी'},
    {'code': 'ne', 'name': 'Nepali', 'native': 'नेपाली'},
    {'code': 'si', 'name': 'Sinhala', 'native': 'සිංහල'},
    {'code': 'my', 'name': 'Burmese', 'native': 'မြန်မာ'},
    {'code': 'km', 'name': 'Khmer', 'native': 'ខ្មែរ'},
    {'code': 'lo', 'name': 'Lao', 'native': 'ລາວ'},
    {'code': 'mn', 'name': 'Mongolian', 'native': 'Монгол'},
    {'code': 'bo', 'name': 'Tibetan', 'native': 'བོད་ཡིག'},
    {'code': 'am', 'name': 'Amharic', 'native': 'አማርኛ'},
    {'code': 'sw', 'name': 'Swahili', 'native': 'Kiswahili'},
    {'code': 'zu', 'name': 'Zulu', 'native': 'isiZulu'},
    {'code': 'af', 'name': 'Afrikaans', 'native': 'Afrikaans'},
    {'code': 'is', 'name': 'Icelandic', 'native': 'Íslenska'},
    {'code': 'mt', 'name': 'Maltese', 'native': 'Malti'},
    {'code': 'cy', 'name': 'Welsh', 'native': 'Cymraeg'},
    {'code': 'ga', 'name': 'Irish', 'native': 'Gaeilge'},
    {'code': 'eu', 'name': 'Basque', 'native': 'Euskara'},
    {'code': 'ca', 'name': 'Catalan', 'native': 'Català'},
    {'code': 'gl', 'name': 'Galician', 'native': 'Galego'},
    {'code': 'br', 'name': 'Breton', 'native': 'Brezhoneg'},
    {'code': 'fy', 'name': 'Frisian', 'native': 'Frysk'},
    {'code': 'lb', 'name': 'Luxembourgish', 'native': 'Lëtzebuergesch'},
    {'code': 'rm', 'name': 'Romansh', 'native': 'Rumantsch'},
    {'code': 'sq', 'name': 'Albanian', 'native': 'Shqip'},
    {'code': 'bs', 'name': 'Bosnian', 'native': 'Bosanski'},
    {'code': 'me', 'name': 'Montenegrin', 'native': 'Crnogorski'},
  ];
}
